name: Go Lint

on:
  pull_request:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  check-changes:
    name: Check for relevant changes
    runs-on: ubuntu-slim
    outputs:
      go: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Check for changes
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        id: changed-files
        with:
          files: |
            **/*.go
            go.mod
            go.sum
            .golangci.yml
            .golangci-lint-version
            .github/workflows/go-lint.yaml

  lint:
    name: Run Go Lint
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.go == 'true'
    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version-file: .golangci-lint-version
